#---------------------------
# Hexo Theme Fluid
# Author: Fluid-dev
# Github: https://github.com/fluid-dev/hexo-theme-fluid
# Docs: https://hexo.fluid-dev.com/docs/en/guide
#---------------------------


#---------------------------
# Global
#---------------------------
favicon: /img/favicon.webp

apple_touch_icon: /img/favicon.webp

tab_title_separator: " - "

force_https: false

code:
  copy_btn: true
  highlight:
    enable: true
    line_number: true
    lib: "highlightjs"
    highlightjs:
      style: "Atom One Dark"
      bg_color: true

fun_features:
  typing:
    enable: true
    typeSpeed: 140
    cursorChar: "_"
    loop: false
  anchorjs:
    enable: true
    element: h1,h2,h3,h4,h5
    placement: right
    visible: hover
    icon: "❡"
  progressbar:
    enable: true
    height_px: 3
    color: "#9f6aeb"
    options: { showSpinner: false, trickleSpeed: 100 }

dark_mode:
  enable: true
  default: dark

# TODO
color:
  body_bg_color: "#eee"
  navbar_bg_color: "#2f4154"
  navbar_text_color: "#fff"
  text_color: "#3c4858"
  sec_text_color: "#718096"
  post_text_color: "#2c3e50"
  post_heading_color: "#1a202c"
  post_link_color: "#0366d6"
  link_hover_color: "#30a9de"
  link_hover_bg_color: "#f8f9fa"
  board_color: "#fff"
  scrollbar_color: "#c4c6c9"
  scrollbar_hover_color: "#a6a6a6"

  body_bg_color_dark: "#181c27"
  navbar_bg_color_dark: "#1f3144"
  navbar_text_color_dark: "#d0d0d0"
  text_color_dark: "#c4c6c9"
  sec_text_color_dark: "#a7a9ad"
  post_text_color_dark: "#c4c6c9"
  post_heading_color_dark: "#c4c6c9"
  post_link_color_dark: "#1589e9"
  link_hover_color_dark: "#30a9de"
  link_hover_bg_color_dark: "#364151"
  board_color_dark: "#252d38"
  scrollbar_color_dark: "#687582"
  scrollbar_hover_color_dark: "#9da8b3"

font:
  font_size: 16px
  font_family: "'JetBrainsMono Nerd Font', 'JetBrains Mono', 'Cascadia Mono', Consolas, monospace"
  letter_spacing: 0.02em
  code_font_size: 95%

custom_js:
custom_css:
custom_head: 
custom_html: 

web_analytics: 
  enable: true
  google: UA-219863528-1
  gtag: G-X80Y7ECC35

lazyload:
  enable: false
  loading_img: 
  onlypost: false
  offset_factor: 2

iconfont: //at.alicdn.com/t/font_1736178_lbnruvf0jn.css


#---------------------------
# Header
#---------------------------
navbar:
  blog_title: "cclin0816's Blog"
  ground_glass:
    enable: true
    px: 3
    alpha: 0.7
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }

search:
  enable: true
  path: /local-search.xml
  generate_path: /local-search.xml
  field: all
  content: true

banner:
  parallax: true
  width_height_ratio: 1.0

scroll_down_arrow:
  enable: true
  banner_height_limit: 60
  scroll_after_turning_page: true

scroll_top_arrow:
  enable: true

# TODO
# Open Graph metadata
# See: https://hexo.io/docs/helpers.html#open-graph
open_graph:
  enable: true
  twitter_card: summary_large_image
  twitter_id: 
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:


#---------------------------
# Footer
#---------------------------
footer:
  content: '
    <a href="https://hexo.io" target="_blank" rel="nofollow noopener"><span>Hexo</span></a>
    <i class="iconfont icon-love"></i>
    <a href="https://github.com/fluid-dev/hexo-theme-fluid" target="_blank" rel="nofollow noopener"><span>Fluid</span></a>
    <i class="iconfont icon-love"></i>
    <a href="https://github.com/cclin0816" target="_blank" rel="nofollow noopener"><span>Me</span></a>'
  statistics:
    enable: false
  beian:
    enable: false


#---------------------------
# Home Page
#---------------------------
index:
  banner_img: /img/miniQ.webp
  banner_img_height: 70
  banner_mask_alpha: 0.5
  slogan:
    enable: true
    text: "Only you can fuck up your life.<br> No one can do it for you."
    api:
      enable: false
      url: ""
      method: "GET"
      headers: {}
      keys: []
  auto_excerpt:
    enable: true
  post_url_target: _self
  post_meta:
    date: true
    category: true
    tag: false
  post_sticky:
    enable: true
    icon: "iconfont icon-bookmark-fill"


#---------------------------
# Post Page
#---------------------------
post:
  banner_img: /img/miniQ.webp
  banner_img_height: 60
  banner_mask_alpha: 0.5
  default_index_img: /img/miniQ-d.webp
  meta:
    author:
      enable: enable
    date:
      enable: true
      format: "LL"
    wordcount:
      enable: false
      format: "{} words"
    min2read:
      enable: false
      format: "{} mins"
      awl: 5
      wpm: 60
    views:
      enable: false
  updated:
    enable: true
    content: "Updated "
    relative: true
  toc:
    enable: true
    headingSelector: "h1,h2,h3,h4"
    collapseDepth: 0
  copyright:
    enable: true
    content: 'Copyright © 2022 cclin0816. All rights reserved.'
  prev_next:
    enable: true
  custom:
    enable: false
    content: ''
  image_zoom:
    enable: true
    img_url_replace: ['-slim', '']
  footnote:
    enable: true
    header: '<h2>Reference</h2>'
  math:
    enable: true
    specific: true
    engine: mathjax
  mermaid:
    enable: true
    specific: true
    options: { theme: 'default' }
  comments:
    enable: true
    type: utterances


#---------------------------
# Comment plugins
#---------------------------
utterances:
  repo: cclin0816/cclin0816.github.io
  issue_term: pathname
  label: utterances
  theme: github-light
  theme_dark: github-dark
  crossorigin: anonymous

#---------------------------
# Archive Page
#---------------------------
archive:
  banner_img: /img/miniQ.webp
  banner_img_height: 60
  banner_mask_alpha: 0.5
  subtitle:


#---------------------------
# Category Page
#---------------------------
category:
  enable: true
  banner_img: /img/miniQ.webp
  banner_img_height: 60
  banner_mask_alpha: 0.5
  subtitle:
  order_by: "name"
  collapse_depth: 0
  post_order_by: "-date"
  post_limit: 8


#---------------------------
# Tag Page
#---------------------------
tag:
  enable: true
  banner_img: /img/miniQ.webp
  banner_img_height: 60
  banner_mask_alpha: 0.5
  subtitle:
  tagcloud:
    min_font: 20
    max_font: 40
    unit: px
    start_color: "#BBBBEE"
    end_color: "#337ab7"


#---------------------------
# About Page
#---------------------------
about:
  enable: true
  banner_img: /img/miniQ.webp
  banner_img_height: 60
  banner_mask_alpha: 0.5
  subtitle:
  avatar: /img/avatar.webp
  name: "cclin0816"
  intro: "這裡拿來放一些作業或是自己弄東西的紀錄<br>依照我得個性，應該也不會太常更新什麼的<br><br>迷你Q是<a href='https://twitter.com/metikyun/' target='_blank' rel='nofollow noopener'> @metikyun </a>的作品<br><br>"
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/cclin0816", tip: "GitHub" }
    - { class: "iconfont icon-twitter-fill", link: "https://twitter.com/cclin0816", tip: "Twitter" }
    - { class: "iconfont icon-mail", link: "mailto:benjamin.cclin@gmail.com", tip: "Email" }


#---------------------------
# Custom Page
#---------------------------
page:
  banner_img: /img/miniQ.webp
  banner_img_height: 60
  banner_mask_alpha: 0.5


#---------------------------
# 404 Page
#---------------------------
page404:
  enable: true
  banner_img: /img/miniQ.webp
  banner_img_height: 100
  banner_mask_alpha: 0.5
  subtitle: "Page not found"


#---------------------------
# Links Page
#---------------------------
links:
  enable: false

static_prefix:

  internal_js: /js
  internal_css: /css
  internal_img: /img

  anchor: https://cdn.jsdelivr.net/npm/anchor-js@4/

  github_markdown: https://cdn.jsdelivr.net/npm/github-markdown-css@4/

  jquery: https://cdn.jsdelivr.net/npm/jquery@3/dist/

  bootstrap: https://cdn.jsdelivr.net/npm/bootstrap@4/dist/

  highlightjs: https://cdn.jsdelivr.net/npm/highlight.js@10/

  prismjs: https://cdn.jsdelivr.net/npm/prismjs@1/

  tocbot: https://cdn.jsdelivr.net/npm/tocbot@4/dist/

  typed: https://cdn.jsdelivr.net/npm/typed.js@2/lib/

  fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3/dist/

  nprogress: https://cdn.jsdelivr.net/npm/nprogress@0/

  mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/

  katex: https://cdn.jsdelivr.net/npm/katex@0/dist/

  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/

  clipboard: https://cdn.jsdelivr.net/npm/clipboard@2/dist/

  mermaid: https://cdn.jsdelivr.net/npm/mermaid@8/dist/

  valine: https://cdn.jsdelivr.net/npm/valine@1/dist/

  waline: https://cdn.jsdelivr.net/npm/@waline/client@1/dist/

  gitalk: https://cdn.jsdelivr.net/npm/gitalk@1/dist/

  disqusjs: https://cdn.jsdelivr.net/npm/disqusjs@1/dist/

  twikoo: https://cdn.jsdelivr.net/npm/twikoo@1/dist/

  hint: https://cdn.jsdelivr.net/npm/hint.css@2/