#---------------------------
# Hexo Theme Fluid
# Author: Fluid-dev
# Github: https://github.com/fluid-dev/hexo-theme-fluid
# Docs: https://hexo.fluid-dev.com/docs/en/guide
#---------------------------


#---------------------------
# Global
#---------------------------
favicon: /img/favicon.webp

apple_touch_icon: /img/favicon.webp

tab_title_separator: " - "

force_https: true

code:
  copy_btn: true
  language:
    enable: true
    default: "TEXT"
  highlight:
    enable: true
    line_number: true
    lib: "prismjs"
    prismjs:
      style: "default"
      style_dark: "okaidia"
      preprocess: true

fun_features:
  typing:
    enable: true
    typeSpeed: 140
    cursorChar: "_"
    loop: false
  anchorjs:
    enable: true
    element: h1,h2,h3,h4
    placement: right
    visible: hover
    icon: "❡"
  progressbar:
    enable: true
    height_px: 3
    color: "#9f6aeb"
    options: { showSpinner: false, trickleSpeed: 100 }

dark_mode:
  enable: true
  default: dark

# TODO
color:
  body_bg_color: "#eee"
  navbar_bg_color: "#2f4154"
  navbar_text_color: "#fff"
  text_color: "#3c4858"
  sec_text_color: "#718096"
  post_text_color: "#2c3e50"
  post_heading_color: "#1a202c"
  post_link_color: "#0366d6"
  link_hover_color: "#30a9de"
  link_hover_bg_color: "#f8f9fa"
  board_color: "#fff"
  scrollbar_color: "#c4c6c9"
  scrollbar_hover_color: "#a6a6a6"

  body_bg_color_dark: "#181c27"
  navbar_bg_color_dark: "#1f3144"
  navbar_text_color_dark: "#d0d0d0"
  text_color_dark: "#c4c6c9"
  sec_text_color_dark: "#a7a9ad"
  post_text_color_dark: "#c4c6c9"
  post_heading_color_dark: "#c4c6c9"
  post_link_color_dark: "#1589e9"
  link_hover_color_dark: "#30a9de"
  link_hover_bg_color_dark: "#364151"
  board_color_dark: "#252d38"
  scrollbar_color_dark: "#687582"
  scrollbar_hover_color_dark: "#9da8b3"

font:
  font_size: 16px
  font_family: "'JetBrains Mono', 'Cascadia Mono', Consolas, monospace"
  letter_spacing: 0.02em
  code_font_size: 95%

custom_js:
custom_css:

web_analytics: 
  enable: true
  follow_dnt: true
  google: UA-219863528-1
  gtag: G-X80Y7ECC35

lazyload:
  enable: false
  loading_img:
  onlypost: false
  offset_factor: 2

iconfont: //at.alicdn.com/t/font_1736178_lbnruvf0jn.css


#---------------------------
# Header
#---------------------------
navbar:
  blog_title: "cclin0816's Blog"
  ground_glass:
    enable: true
    px: 3
    alpha: 0.7
  menu:
    # - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    # - { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }

search:
  enable: true
  path: /local-search.xml
  generate_path: /local-search.xml
  field: all
  content: true

banner:
  parallax: true
  width_height_ratio: 1.0

scroll_down_arrow:
  enable: true
  banner_height_limit: 60
  scroll_after_turning_page: true

scroll_top_arrow:
  enable: true

open_graph:
  enable: true
  twitter_card: summary
  twitter_id: '@cclin0816'
  twitter_site: '@cclin0816'
  google_plus:
  fb_admins:
  fb_app_id:


#---------------------------
# Footer
#---------------------------
footer:
  content: '
    <a href="https://hexo.io" target="_blank" rel="nofollow noopener"><span>Hexo</span></a>
    <i class="iconfont icon-love"></i>
    <a href="https://github.com/fluid-dev/hexo-theme-fluid" target="_blank" rel="nofollow noopener"><span>Fluid</span></a>
    <i class="iconfont icon-love"></i>
    <a href="https://github.com/cclin0816" target="_blank" rel="nofollow noopener"><span>Me</span></a>'
  statistics:
    enable: false
  beian:
    enable: false


#---------------------------
# Home Page
#---------------------------
index:
  banner_img: /img/miniQ.webp
  banner_img_height: 70
  banner_mask_alpha: 0.4
  slogan:
    enable: true
    text: "Only you can fuck up your life.<br>No one can do it for you.<br>"
    api:
      enable: false
      url: ""
      method: "GET"
      headers: {}
      keys: []
  auto_excerpt:
    enable: true
  post_url_target: _self
  post_meta:
    date: true
    category: true
    tag: false
  post_sticky:
    enable: true
    icon: "iconfont icon-bookmark-fill"


#---------------------------
# Post Page
#---------------------------
post:
  banner_img: /img/miniQ.webp
  banner_img_height: 40
  banner_mask_alpha: 0.4
  default_index_img: /img/miniQ-d.webp
  meta:
    author:
      enable: true
    date:
      enable: true
      format: "LL"
    wordcount:
      enable: false
    min2read:
      enable: false
      awl: 5
      wpm: 60
    views:
      enable: false
  updated:
    enable: true
    relative: true
    note_class: info
  category_bar:
    enable: true
    specific: true
    placement: right
    post_order_by: "date"
    post_limit: 5
  toc:
    enable: true
    placement: left
    headingSelector: "h1,h2,h3,h4"
    collapseDepth: 0
  copyright:
    enable: true
    license: 'BY-NC-SA'
    author:
      enable: true
    post_date:
      enable: true
      format: "LL"
    update_date:
      enable: false
      format: "LL"
  prev_next:
    enable: true
  image_caption:
    enable: false
  image_zoom:
    enable: true
    img_url_replace: ['-slim', '']
  footnote:
    enable: true
    header: '<h2>Reference</h2>'
  math:
    enable: true
    specific: true
    engine: mathjax
  mermaid:
    enable: true
    specific: true
    options: { theme: 'dark' }
  comments:
    enable: true
    type: utterances


#---------------------------
# Comment plugins
#---------------------------
utterances:
  repo: cclin0816/cclin0816.github.io
  issue_term: pathname
  label: utterances
  theme: github-light
  theme_dark: github-dark
  crossorigin: anonymous

#---------------------------
# Archive Page
#---------------------------
archive:
  banner_img: /img/miniQ.webp
  banner_img_height: 40
  banner_mask_alpha: 0.4


#---------------------------
# Category Page
#---------------------------
category:
  enable: true
  banner_img: /img/miniQ.webp
  banner_img_height: 40
  banner_mask_alpha: 0.4
  order_by: "-length"
  collapse_depth: 0
  post_order_by: "date"
  post_limit: 5


#---------------------------
# Tag Page
#---------------------------
tag:
  enable: true
  banner_img: /img/miniQ.webp
  banner_img_height: 40
  banner_mask_alpha: 0.4
  tagcloud:
    min_font: 20
    max_font: 30
    unit: px
    start_color: "#b7d9e7"
    end_color: "#d3b9e5"


#---------------------------
# About Page
#---------------------------
about:
  enable: true
  banner_img: /img/miniQ.webp
  banner_img_height: 50
  banner_mask_alpha: 0.4
  avatar: /img/avatar.webp
  name: "cclin0816"
  intro: "拿來放一些奇怪的東西，應該不會太常更新<br>文筆很爛請見諒，內容有誤歡迎發 issue<br><br>迷你Q是<a href='https://twitter.com/metikyun/' target='_blank' rel='nofollow noopener'> @metikyun </a>的作品<br><br>"
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/cclin0816", tip: "GitHub" }
    - { class: "iconfont icon-twitter-fill", link: "https://twitter.com/cclin0816", tip: "Twitter" }
    - { class: "iconfont icon-mail", link: "mailto:benjamin.cclin@gmail.com", tip: "Email" }


#---------------------------
# Custom Page
#---------------------------
page:
  banner_img: /img/miniQ.webp
  banner_img_height: 40
  banner_mask_alpha: 0.4


#---------------------------
# 404 Page
#---------------------------
page404:
  enable: true
  banner_img: /img/miniQ.webp
  banner_img_height: 90
  banner_mask_alpha: 0.4
  redirect_delay: 7000


#---------------------------
# Links Page
#---------------------------
links:
  enable: false
  banner_img: /img/miniQ.webp
  banner_img_height: 40
  banner_mask_alpha: 0.4
  items:
  onerror_avatar: /img/avatar.webp
  custom:
    enable: false
    content: ''
  comments:
    enable: false
    type: giscus

static_prefix:

  internal_js: /js
  internal_css: /css
  internal_img: /img

  anchor: https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.3.1/

  github_markdown: https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/4.0.0/

  jquery: https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/

  bootstrap: https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.2/

  highlightjs: https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.1/js/

  prismjs: https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/

  tocbot: https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.18.2/

  typed: https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.12/

  fancybox: https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/

  nprogress: https://cdnjs.cloudflare.com/ajax/libs/nprogress/0.2.0/

  mathjax: https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/

  katex: https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.2/

  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/

  clipboard: https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.11/

  mermaid: https://cdnjs.cloudflare.com/ajax/libs/mermaid/9.1.7/

  valine: https://cdnjs.cloudflare.com/ajax/libs/valine/1.5.1/

  waline: https://cdnjs.cloudflare.com/ajax/libs/waline/2.11.1/

  gitalk: https://cdnjs.cloudflare.com/ajax/libs/gitalk/1.8.0/

  disqusjs: https://cdnjs.cloudflare.com/ajax/libs/discuss/1.1.8/dist/

  twikoo: https://cdnjs.cloudflare.com/ajax/libs/twikoo/1.6.7/

  hint: https://cdnjs.cloudflare.com/ajax/libs/hint.css/2.7.0/