# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: cclin0816's Blog
subtitle: 
description: personal blog
keywords: cclin0816
author: cclin0816
language: en
timezone: Asia/Taipei

# URL
url: https://cclin0816.github.io
root: 
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false
  trailing_html: false

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: []
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: false

highlight:
  enable: false
  auto_detect: false
  line_number: true
  line_threshold: 0
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  line_threshold: 0
  tab_replace: ''

# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  pagination_dir: page

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
theme: fluid
deploy:
  type: git
  repo: https://github.com/cclin0816/cclin0816.github.io
  branch: main
  message: 
meta_generator: true

# Include / Exclude files or folders
include:
  - ".nojekyll"
# exclude:
# ignore:
